language: emacs-lisp

cache: apt

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip

install:
  - cask install

env:
  - EVM_EMACS=emacs-26.2-travis

script:
  - cask --version
  - $(which emacs) --version
  - EMACS=$(which emacs) make test
