;; -*- emacs-lisp -*-
(source gnu)
(source melpa)

(package-file "${project-name}.el")

(files "*.el" "doc/*.texi" (:exclude ".dir-locals.el"))

(development
 (depends-on "dash")
 (depends-on "ert-runner"))
