;; -*- emacs-lisp -*-
(source gnu)
(source melpa-stable)

(depends-on "dash" "2.17.0")

(package-file "${project-name}.el")

(files "*.el" "doc/*.texi" (:exclude ".dir-locals.el"))

(development
 (depends-on "package-lint")
 (depends-on "ert-runner"))
